# Site settings
title: Daniel Sperry Portfolio
description: I try to keep my digital footprint in one place
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Sperry
about_description: Adapt what is useful, reject what is useless, and add what is specifically your own.
user_title: Web Developer
email: danny.sperry@gmail.com
github_username:  dannysperry

# Google-analytics
google-analytics:
  id: "UA-93991983-1"

exclude: ['package.json', 'src' , 'node_modules']
